name: flutter_modules
description: A library for implementing modularity in Flutter apps.
version: 2.0.0
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependency Injection
  dart_dependencies_manager:
    git:
      url: git@github.com:fabriziocacicia/dart_dependencies_manager.git
      ref: v1.1.0

dev_dependencies:
  # Linting and Code analysis
  flutter_lint_rules:
    git:
      url: git@github.com:fabriziocacicia/flutter_lint_rules.git
      ref: v0.0.4

flutter:


